[versions]

agp = "9.0.0"
kotlin = "2.3.0"

ksp = "2.3.4"

gms = "4.4.4"

crashlyticsPlugin = "3.0.6"
performancePlugin = "2.0.2"

coreKtx = "1.17.0"
lifecycle = "2.10.0"

composeBom = "2026.01.01"
composeActivity = "1.12.3"
composeNavigation = "2.9.7"

accompanist = "0.37.3"

splashScreen = "1.2.0"

reorderableLists = "3.0.0"

coroutines = "1.10.2"

room = "2.8.4"

hilt = "2.59.1"
hiltX = "1.3.0"

lottie = "6.7.1"

coil = "3.3.0"

kotlinxSerializationJson = "1.10.0"

blur = "1.7.1"

zoom = "1.4.0"

exoplayer = "1.9.2"

calendar = "2.10.0"

dataStore = "1.2.0"

biometric = "1.4.0-alpha02"

mail = "1.6.8"

googleAuth = "21.1.1"
credentials = "1.5.0"
googleid = "1.2.0"

googleDrive = "v3-rev197-1.25.0"
googleDriveGms = "17.0.0"

googleLocationGms = "21.3.0"

retrofit = "3.0.0"
loggingInterceptor = "5.3.2"
kotlinSerializationConverter = "1.0.0"

exifinterface = "1.4.2"

workManager = "2.11.1"

firebaseBom = "34.9.0"

[libraries]

coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
composeRuntime = { module = "androidx.compose.runtime:runtime" }
composeFoundation = { module = "androidx.compose.foundation:foundation" }
composeUi = { module = "androidx.compose.ui:ui" }
composeAnimation = { module = "androidx.compose.animation:animation" }
composeGraphics = { module = "androidx.compose.ui:ui-graphics" }
composeToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
composeTooling = { module = "androidx.compose.ui:ui-tooling" }
material3 = { module = "androidx.compose.material3:material3" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeNavigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

reorderableLists = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderableLists" }

permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }

coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }


room = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltNavigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltX" }
hiltWork = { module = "androidx.hilt:hilt-work", version.ref = "hiltX" }
hiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltX" }
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilVideo = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil" }
coilGif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }

zoom = { module = "io.github.panpf.zoomimage:zoomimage-compose", version.ref = "zoom" }
zoomCoil = { module = "io.github.panpf.zoomimage:zoomimage-compose-coil3", version.ref = "zoom" }

blur = { module = "dev.chrisbanes.haze:haze", version.ref = "blur" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
exoplayerUi = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }

calendar = { module = "com.kizitonwose.calendar:compose", version.ref = "calendar" }

dataStore = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }

mail = { module = "com.sun.mail:android-mail", version.ref = "mail" }
mailActivaliton = { module = "com.sun.mail:android-activation", version.ref = "mail" }

googleAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "googleAuth" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentialsAuth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

googleDrive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleDrive" }
googleDriveGms = { module = "com.google.android.gms:play-services-drive", version.ref = "googleDriveGms" }
googleLocationGms = { module = "com.google.android.gms:play-services-location", version.ref = "googleLocationGms" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
kotlinSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinSerializationConverter" }

exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

workManager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
analytics = { module = "com.google.firebase:firebase-analytics" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
performance = { module = "com.google.firebase:firebase-perf" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }


[plugins]

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
performancePlugin = { id = "com.google.firebase.firebase-perf", version.ref = "performancePlugin" }